//
// File generated by rootcint at Wed May 28 10:08:20 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME TDDVCSGenDict
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "TDDVCSGenDict.h"

#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void TGenPart_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TGenPart(void *p = 0);
   static void *newArray_TGenPart(Long_t size, void *p);
   static void delete_TGenPart(void *p);
   static void deleteArray_TGenPart(void *p);
   static void destruct_TGenPart(void *p);
   static void streamer_TGenPart(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TGenPart*)
   {
      ::TGenPart *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TGenPart >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TGenPart", ::TGenPart::Class_Version(), "./TDDVCSGen.h", 30,
                  typeid(::TGenPart), DefineBehavior(ptr, ptr),
                  &::TGenPart::Dictionary, isa_proxy, 0,
                  sizeof(::TGenPart) );
      instance.SetNew(&new_TGenPart);
      instance.SetNewArray(&newArray_TGenPart);
      instance.SetDelete(&delete_TGenPart);
      instance.SetDeleteArray(&deleteArray_TGenPart);
      instance.SetDestructor(&destruct_TGenPart);
      instance.SetStreamerFunc(&streamer_TGenPart);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TGenPart*)
   {
      return GenerateInitInstanceLocal((::TGenPart*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TGenPart*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

namespace ROOT {
   void TDDVCSGen_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_TDDVCSGen(void *p = 0);
   static void *newArray_TDDVCSGen(Long_t size, void *p);
   static void delete_TDDVCSGen(void *p);
   static void deleteArray_TDDVCSGen(void *p);
   static void destruct_TDDVCSGen(void *p);
   static void streamer_TDDVCSGen(TBuffer &buf, void *obj);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::TDDVCSGen*)
   {
      ::TDDVCSGen *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::TDDVCSGen >(0);
      static ::ROOT::TGenericClassInfo 
         instance("TDDVCSGen", ::TDDVCSGen::Class_Version(), "./TDDVCSGen.h", 94,
                  typeid(::TDDVCSGen), DefineBehavior(ptr, ptr),
                  &::TDDVCSGen::Dictionary, isa_proxy, 0,
                  sizeof(::TDDVCSGen) );
      instance.SetNew(&new_TDDVCSGen);
      instance.SetNewArray(&newArray_TDDVCSGen);
      instance.SetDelete(&delete_TDDVCSGen);
      instance.SetDeleteArray(&deleteArray_TDDVCSGen);
      instance.SetDestructor(&destruct_TDDVCSGen);
      instance.SetStreamerFunc(&streamer_TDDVCSGen);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::TDDVCSGen*)
   {
      return GenerateInitInstanceLocal((::TDDVCSGen*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::TDDVCSGen*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *TGenPart::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TGenPart::Class_Name()
{
   return "TGenPart";
}

//______________________________________________________________________________
const char *TGenPart::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TGenPart*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TGenPart::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TGenPart*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TGenPart::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TGenPart*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TGenPart::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TGenPart*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
TClass *TDDVCSGen::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *TDDVCSGen::Class_Name()
{
   return "TDDVCSGen";
}

//______________________________________________________________________________
const char *TDDVCSGen::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TDDVCSGen*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int TDDVCSGen::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::TDDVCSGen*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void TDDVCSGen::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TDDVCSGen*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *TDDVCSGen::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::TDDVCSGen*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void TDDVCSGen::Streamer(TBuffer &R__b)
{
   // Stream an object of class TDDVCSGen.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TObject::Streamer(R__b);
      fk.Streamer(R__b);
      fkp.Streamer(R__b);
      fpi.Streamer(R__b);
      fpf.Streamer(R__b);
      fp.Streamer(R__b);
      fq1.Streamer(R__b);
      fq2.Streamer(R__b);
      fq2CM.Streamer(R__b);
      fq.Streamer(R__b);
      fL1.Streamer(R__b);
      fL2.Streamer(R__b);
      fL1CM.Streamer(R__b);
      fL2CM.Streamer(R__b);
      fDelta.Streamer(R__b);
      fBoostq2.Streamer(R__b);
      R__b >> fGkp;
      R__b >> fGq2;
      R__b >> fGL1;
      R__b >> fDThetaE;
      R__b >> fDPhiE;
      R__b >> fDPE;
      R__b >> fDThetaQ2;
      R__b >> fDPhiQ2;
      R__b >> fQ2;
      R__b >> fxbj;
      R__b >> fEta;
      R__b >> fXi;
      R__b >> fAngle;
      R__b >> fMTarg;
      R__b.CheckByteCount(R__s, R__c, TDDVCSGen::IsA());
   } else {
      R__c = R__b.WriteVersion(TDDVCSGen::IsA(), kTRUE);
      TObject::Streamer(R__b);
      fk.Streamer(R__b);
      fkp.Streamer(R__b);
      fpi.Streamer(R__b);
      fpf.Streamer(R__b);
      fp.Streamer(R__b);
      fq1.Streamer(R__b);
      fq2.Streamer(R__b);
      fq2CM.Streamer(R__b);
      fq.Streamer(R__b);
      fL1.Streamer(R__b);
      fL2.Streamer(R__b);
      fL1CM.Streamer(R__b);
      fL2CM.Streamer(R__b);
      fDelta.Streamer(R__b);
      fBoostq2.Streamer(R__b);
      R__b << fGkp;
      R__b << fGq2;
      R__b << fGL1;
      R__b << fDThetaE;
      R__b << fDPhiE;
      R__b << fDPE;
      R__b << fDThetaQ2;
      R__b << fDPhiQ2;
      R__b << fQ2;
      R__b << fxbj;
      R__b << fEta;
      R__b << fXi;
      R__b << fAngle;
      R__b << fMTarg;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TDDVCSGen::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TDDVCSGen.
      TClass *R__cl = ::TDDVCSGen::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fk", &fk);
      R__insp.InspectMember(fk, "fk.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fkp", &fkp);
      R__insp.InspectMember(fkp, "fkp.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpi", &fpi);
      R__insp.InspectMember(fpi, "fpi.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fpf", &fpf);
      R__insp.InspectMember(fpf, "fpf.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fp", &fp);
      R__insp.InspectMember(fp, "fp.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fq1", &fq1);
      R__insp.InspectMember(fq1, "fq1.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fq2", &fq2);
      R__insp.InspectMember(fq2, "fq2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fq2CM", &fq2CM);
      R__insp.InspectMember(fq2CM, "fq2CM.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fq", &fq);
      R__insp.InspectMember(fq, "fq.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fL1", &fL1);
      R__insp.InspectMember(fL1, "fL1.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fL2", &fL2);
      R__insp.InspectMember(fL2, "fL2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fL1CM", &fL1CM);
      R__insp.InspectMember(fL1CM, "fL1CM.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fL2CM", &fL2CM);
      R__insp.InspectMember(fL2CM, "fL2CM.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDelta", &fDelta);
      R__insp.InspectMember(fDelta, "fDelta.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fBoostq2", &fBoostq2);
      R__insp.InspectMember(fBoostq2, "fBoostq2.");
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGkp", &fGkp);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGq2", &fGq2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fGL1", &fGL1);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDThetaE", &fDThetaE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDPhiE", &fDPhiE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDPE", &fDPE);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDThetaQ2", &fDThetaQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fDPhiQ2", &fDPhiQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fQ2", &fQ2);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fxbj", &fxbj);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEta", &fEta);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fXi", &fXi);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fAngle", &fAngle);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMTarg", &fMTarg);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TDDVCSGen(void *p) {
      return  p ? new(p) ::TDDVCSGen : new ::TDDVCSGen;
   }
   static void *newArray_TDDVCSGen(Long_t nElements, void *p) {
      return p ? new(p) ::TDDVCSGen[nElements] : new ::TDDVCSGen[nElements];
   }
   // Wrapper around operator delete
   static void delete_TDDVCSGen(void *p) {
      delete ((::TDDVCSGen*)p);
   }
   static void deleteArray_TDDVCSGen(void *p) {
      delete [] ((::TDDVCSGen*)p);
   }
   static void destruct_TDDVCSGen(void *p) {
      typedef ::TDDVCSGen current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TDDVCSGen(TBuffer &buf, void *obj) {
      ((::TDDVCSGen*)obj)->::TDDVCSGen::Streamer(buf);
   }
} // end of namespace ROOT for class ::TDDVCSGen

//______________________________________________________________________________
void TGenPart::Streamer(TBuffer &R__b)
{
   // Stream an object of class TGenPart.

   UInt_t R__s, R__c;
   if (R__b.IsReading()) {
      Version_t R__v = R__b.ReadVersion(&R__s, &R__c); if (R__v) { }
      TRandom3::Streamer(R__b);
      R__b >> fThMin;
      R__b >> fThMax;
      R__b >> fPhMin;
      R__b >> fPhMax;
      R__b >> fEMin;
      R__b >> fEMax;
      R__b >> fMass;
      R__b >> fLorVect;
      R__b.CheckByteCount(R__s, R__c, TGenPart::IsA());
   } else {
      R__c = R__b.WriteVersion(TGenPart::IsA(), kTRUE);
      TRandom3::Streamer(R__b);
      R__b << fThMin;
      R__b << fThMax;
      R__b << fPhMin;
      R__b << fPhMax;
      R__b << fEMin;
      R__b << fEMax;
      R__b << fMass;
      R__b << fLorVect;
      R__b.SetByteCount(R__c, kTRUE);
   }
}

//______________________________________________________________________________
void TGenPart::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class TGenPart.
      TClass *R__cl = ::TGenPart::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fThMin", &fThMin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fThMax", &fThMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPhMin", &fPhMin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fPhMax", &fPhMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEMin", &fEMin);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fEMax", &fEMax);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fMass", &fMass);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "*fLorVect", &fLorVect);
      TRandom3::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_TGenPart(void *p) {
      return  p ? new(p) ::TGenPart : new ::TGenPart;
   }
   static void *newArray_TGenPart(Long_t nElements, void *p) {
      return p ? new(p) ::TGenPart[nElements] : new ::TGenPart[nElements];
   }
   // Wrapper around operator delete
   static void delete_TGenPart(void *p) {
      delete ((::TGenPart*)p);
   }
   static void deleteArray_TGenPart(void *p) {
      delete [] ((::TGenPart*)p);
   }
   static void destruct_TGenPart(void *p) {
      typedef ::TGenPart current_t;
      ((current_t*)p)->~current_t();
   }
   // Wrapper around a custom streamer member function.
   static void streamer_TGenPart(TBuffer &buf, void *obj) {
      ((::TGenPart*)obj)->::TGenPart::Streamer(buf);
   }
} // end of namespace ROOT for class ::TGenPart

/********************************************************
* TDDVCSGenDict.C
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableTDDVCSGenDict();

extern "C" void G__set_cpp_environmentTDDVCSGenDict() {
  G__add_compiledheader("TObject.h");
  G__add_compiledheader("TMemberInspector.h");
  G__add_compiledheader("TDDVCSGen.h");
  G__cpp_reset_tagtableTDDVCSGenDict();
}
#include <new>
extern "C" int G__cpp_dllrevTDDVCSGenDict() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* TGenPart */
static int G__TDDVCSGenDict_228_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TGenPart* p = NULL;
   char* gvp = (char*) G__getgvp();
   //m: 1
   if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
     p = new TGenPart((TLorentzVector*) G__int(libp->para[0]));
   } else {
     p = new((void*) gvp) TGenPart((TLorentzVector*) G__int(libp->para[0]));
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TGenPart* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TGenPart[n];
     } else {
       p = new((void*) gvp) TGenPart[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TGenPart;
     } else {
       p = new((void*) gvp) TGenPart;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TGenPart*) G__getstructoffset())->Generate();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TGenPart*) G__getstructoffset())->Generate((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TGenPart*) G__getstructoffset())->Generate((Double_t) G__double(libp->para[0]));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TGenPart*) G__getstructoffset())->GenerateDir(*((TVector3*) G__int(libp->para[0])));
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetThMin((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetThMax((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetPhiMin((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetPhiMax((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetEMin((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetEMax((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TGenPart*) G__getstructoffset())->SetMass((Double_t) G__double(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TGenPart*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TGenPart::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TGenPart::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TGenPart::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TGenPart::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TGenPart*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TGenPart::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TGenPart::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TGenPart::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_228_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TGenPart::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TDDVCSGenDict_228_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TGenPart* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TGenPart(*(TGenPart*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TGenPart G__TTGenPart;
static int G__TDDVCSGenDict_228_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TGenPart*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TGenPart*) (soff+(sizeof(TGenPart)*i)))->~G__TTGenPart();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TGenPart*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TGenPart*) (soff))->~G__TTGenPart();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TDDVCSGenDict_228_0_29(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TGenPart* dest = (TGenPart*) G__getstructoffset();
   *dest = *(TGenPart*) libp->para[0].ref;
   const TGenPart& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* TDDVCSGen */
static int G__TDDVCSGenDict_229_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDDVCSGen* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TDDVCSGen[n];
     } else {
       p = new((void*) gvp) TDDVCSGen[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new TDDVCSGen;
     } else {
       p = new((void*) gvp) TDDVCSGen;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->GenerateDDVCS();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->GenerateDDVCSFlat();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->SetFourVect((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->SetBeam(*(TLorentzVector*) libp->para[0].ref);
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->SetScattered(*(TLorentzVector*) libp->para[0].ref);
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->SetBeam((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->SetBeam((Double_t) G__double(libp->para[0]));
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->SetScattered((Double_t) G__double(libp->para[0]), (Double_t) G__double(libp->para[1])
, (Double_t) G__double(libp->para[2]), (Double_t) G__double(libp->para[3]));
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->GenerateEvent();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_11(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->GenerateScattered();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_12(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->GenerateQ2();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_13(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->Q1();
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->Q();
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->Delta();
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->Deltap();
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      {
         TLorentzVector* pobj;
         TLorentzVector xobj = ((TDDVCSGen*) G__getstructoffset())->P();
         pobj = new TLorentzVector(xobj);
         result7->obj.i = (long) ((void*) pobj);
         result7->ref = result7->obj.i;
         G__store_tempobject(*result7);
      }
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TDDVCSGen*) G__getstructoffset())->Xi());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TDDVCSGen*) G__getstructoffset())->Eta());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TDDVCSGen*) G__getstructoffset())->Q2());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TDDVCSGen*) G__getstructoffset())->xbj());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_22(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letdouble(result7, 100, (double) ((TDDVCSGen*) G__getstructoffset())->t());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_23(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->Compute();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_24(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->Print();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_25(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) TDDVCSGen::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_26(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDDVCSGen::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_27(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) TDDVCSGen::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_28(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      TDDVCSGen::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_32(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((TDDVCSGen*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_33(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDDVCSGen::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_34(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDDVCSGen::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_35(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) TDDVCSGen::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__TDDVCSGenDict_229_0_36(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) TDDVCSGen::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__TDDVCSGenDict_229_0_37(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   TDDVCSGen* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new TDDVCSGen(*(TDDVCSGen*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef TDDVCSGen G__TTDDVCSGen;
static int G__TDDVCSGenDict_229_0_38(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (TDDVCSGen*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((TDDVCSGen*) (soff+(sizeof(TDDVCSGen)*i)))->~G__TTDDVCSGen();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (TDDVCSGen*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((TDDVCSGen*) (soff))->~G__TTDDVCSGen();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__TDDVCSGenDict_229_0_39(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   TDDVCSGen* dest = (TDDVCSGen*) G__getstructoffset();
   *dest = *(TDDVCSGen*) libp->para[0].ref;
   const TDDVCSGen& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* TGenPart */

/* TDDVCSGen */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncTDDVCSGenDict {
 public:
  G__Sizep2memfuncTDDVCSGenDict(): p(&G__Sizep2memfuncTDDVCSGenDict::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncTDDVCSGenDict::*p)();
};

size_t G__get_sizep2memfuncTDDVCSGenDict()
{
  G__Sizep2memfuncTDDVCSGenDict a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceTDDVCSGenDict() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart))) {
     TGenPart *G__Lderived;
     G__Lderived=(TGenPart*)0x1000;
     {
       TRandom3 *G__Lpbase=(TRandom3*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),G__get_linked_tagnum(&G__TDDVCSGenDictLN_TRandom3),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
     {
       TRandom *G__Lpbase=(TRandom*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),G__get_linked_tagnum(&G__TDDVCSGenDictLN_TRandom),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TNamed *G__Lpbase=(TNamed*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),G__get_linked_tagnum(&G__TDDVCSGenDictLN_TNamed),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),G__get_linked_tagnum(&G__TDDVCSGenDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,0);
     }
   }
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen))) {
     TDDVCSGen *G__Lderived;
     G__Lderived=(TDDVCSGen*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen),G__get_linked_tagnum(&G__TDDVCSGenDictLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableTDDVCSGenDict() {

   /* Setting up typedef entry */
   G__search_typename2("Double_t",100,-1,0,-1);
   G__setnewtype(-1,"Double 8 bytes",0);
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTBaselEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTBase<Double_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTBaselEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TVectorTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TVectorT<Double_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TVectorTlEdoublegR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixT<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTColumn_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTFlat_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTSub_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTSparseRow_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag_const<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTSparseDiag_constlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTRow<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTColumn<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTColumnlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTDiag<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTFlat<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTFlatlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSub<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTSublEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseRow<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTSparseRowlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TMatrixTSparseDiag<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TMatrixTSparseDiaglEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementActionT<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TElementActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("TElementPosActionT<Float_t>",117,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TElementPosActionTlEfloatgR),0,-1);
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* TGenPart */
static void G__setup_memvarTGenPart(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart));
   { TGenPart *p; p=(TGenPart*)0x1000; if (p) { }
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fThMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fThMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fPhMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fPhMax=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fEMin=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fEMax=",0,"Degrees");
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fMass=",0,"GeV");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fLorVect=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}


   /* TDDVCSGen */
static void G__setup_memvarTDDVCSGen(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen));
   { TDDVCSGen *p; p=(TDDVCSGen*)0x1000; if (p) { }
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fk=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fkp=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fpi=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fpf=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fp=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fq1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fq2=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fq2CM=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fq=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fL1=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fL2=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fL1CM=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fL2CM=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector),-1,-1,2,"fDelta=",0,(char*)NULL);
   G__memvar_setup((void*)0,117,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TVector3),-1,-1,2,"fBoostq2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),-1,-1,2,"fGkp=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),-1,-1,2,"fGq2=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart),-1,-1,2,"fGL1=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fDThetaE=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fDPhiE=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fDPE=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fDThetaQ2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fDPhiQ2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fQ2=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fxbj=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fEta=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fXi=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fAngle=",0,(char*)NULL);
   G__memvar_setup((void*)0,100,0,0,-1,G__defined_typename("Double_t"),-1,2,"fMTarg=",0,(char*)NULL);
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__TDDVCSGenDictLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarTDDVCSGenDict() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncTGenPart(void) {
   /* TGenPart */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart));
   G__memfunc_setup("TGenPart",773,G__TDDVCSGenDict_228_0_1, 105, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart), -1, 0, 1, 1, 1, 0, "U 'TLorentzVector' - 0 - lv", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("TGenPart",773,G__TDDVCSGenDict_228_0_2, 105, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Generate",811,G__TDDVCSGenDict_228_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Generate",811,G__TDDVCSGenDict_228_0_4, 121, -1, -1, 0, 2, 1, 1, 0, 
"d - 'Double_t' 0 - Emin d - 'Double_t' 0 - Emax", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Generate",811,G__TDDVCSGenDict_228_0_5, 121, -1, -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - P", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateDir",1098,G__TDDVCSGenDict_228_0_6, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TVector3' - 0 - dir", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetThMin",780,G__TDDVCSGenDict_228_0_7, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetThMax",782,G__TDDVCSGenDict_228_0_8, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPhiMin",881,G__TDDVCSGenDict_228_0_9, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetPhiMax",883,G__TDDVCSGenDict_228_0_10, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEMin",661,G__TDDVCSGenDict_228_0_11, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetEMax",663,G__TDDVCSGenDict_228_0_12, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetMass",704,G__TDDVCSGenDict_228_0_13, 100, -1, G__defined_typename("Double_t"), 0, 1, 1, 1, 0, "d - 'Double_t' 0 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__TDDVCSGenDict_228_0_14, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TDDVCSGenDict_228_0_15, 85, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TGenPart::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TDDVCSGenDict_228_0_16, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGenPart::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TDDVCSGenDict_228_0_17, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TGenPart::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TDDVCSGenDict_228_0_18, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TGenPart::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TDDVCSGenDict_228_0_22, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TDDVCSGenDict_228_0_23, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGenPart::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TDDVCSGenDict_228_0_24, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TGenPart::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TDDVCSGenDict_228_0_25, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TGenPart::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TDDVCSGenDict_228_0_26, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TGenPart::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TGenPart", 773, G__TDDVCSGenDict_228_0_27, (int) ('i'), G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart), -1, 0, 1, 1, 1, 0, "u 'TGenPart' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TGenPart", 899, G__TDDVCSGenDict_228_0_28, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TDDVCSGenDict_228_0_29, (int) ('u'), G__get_linked_tagnum(&G__TDDVCSGenDictLN_TGenPart), -1, 1, 1, 1, 1, 0, "u 'TGenPart' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}

static void G__setup_memfuncTDDVCSGen(void) {
   /* TDDVCSGen */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen));
   G__memfunc_setup("TDDVCSGen",738,G__TDDVCSGenDict_229_0_1, 105, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateDDVCS",1183,G__TDDVCSGenDict_229_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateDDVCSFlat",1574,G__TDDVCSGenDict_229_0_3, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetFourVect",1114,G__TDDVCSGenDict_229_0_4, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - E d - 'Double_t' 0 - kx "
"d - 'Double_t' 0 - ky d - 'Double_t' 0 - kz", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetBeam",673,G__TDDVCSGenDict_229_0_5, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 1, 1, 1, 0, "u 'TLorentzVector' - 1 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetScattered",1227,G__TDDVCSGenDict_229_0_6, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 1, 1, 1, 0, "u 'TLorentzVector' - 1 - v", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetBeam",673,G__TDDVCSGenDict_229_0_7, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - px d - 'Double_t' 0 - py "
"d - 'Double_t' 0 - pz d - 'Double_t' 0 - E", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetBeam",673,G__TDDVCSGenDict_229_0_8, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 1, 1, 1, 0, "d - 'Double_t' 0 - E", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("SetScattered",1227,G__TDDVCSGenDict_229_0_9, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 4, 1, 1, 0, 
"d - 'Double_t' 0 - px d - 'Double_t' 0 - py "
"d - 'Double_t' 0 - pz d - 'Double_t' 0 - E", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateEvent",1325,G__TDDVCSGenDict_229_0_10, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateScattered",1738,G__TDDVCSGenDict_229_0_11, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GenerateQ2",942,G__TDDVCSGenDict_229_0_12, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Q1",130,G__TDDVCSGenDict_229_0_13, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Q",81,G__TDDVCSGenDict_229_0_14, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Delta",490,G__TDDVCSGenDict_229_0_15, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Deltap",602,G__TDDVCSGenDict_229_0_16, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("P",80,G__TDDVCSGenDict_229_0_17, 117, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TLorentzVector), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Xi",193,G__TDDVCSGenDict_229_0_18, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Eta",282,G__TDDVCSGenDict_229_0_19, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Q2",131,G__TDDVCSGenDict_229_0_20, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("xbj",324,G__TDDVCSGenDict_229_0_21, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("t",116,G__TDDVCSGenDict_229_0_22, 100, -1, G__defined_typename("Double_t"), 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Compute",733,G__TDDVCSGenDict_229_0_23, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Print",525,G__TDDVCSGenDict_229_0_24, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__TDDVCSGenDict_229_0_25, 85, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&TDDVCSGen::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__TDDVCSGenDict_229_0_26, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDDVCSGen::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__TDDVCSGenDict_229_0_27, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&TDDVCSGen::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__TDDVCSGenDict_229_0_28, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&TDDVCSGen::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__TDDVCSGenDictLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__TDDVCSGenDict_229_0_32, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__TDDVCSGenDict_229_0_33, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDDVCSGen::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__TDDVCSGenDict_229_0_34, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDDVCSGen::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__TDDVCSGenDict_229_0_35, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&TDDVCSGen::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__TDDVCSGenDict_229_0_36, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&TDDVCSGen::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("TDDVCSGen", 738, G__TDDVCSGenDict_229_0_37, (int) ('i'), G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen), -1, 0, 1, 1, 1, 0, "u 'TDDVCSGen' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~TDDVCSGen", 864, G__TDDVCSGenDict_229_0_38, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__TDDVCSGenDict_229_0_39, (int) ('u'), G__get_linked_tagnum(&G__TDDVCSGenDictLN_TDDVCSGen), -1, 1, 1, 1, 1, 0, "u 'TDDVCSGen' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncTDDVCSGenDict() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {
}

static void G__cpp_setup_global2() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalTDDVCSGenDict() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
  G__cpp_setup_global2();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {
}

static void G__cpp_setup_func13() {
}

static void G__cpp_setup_func14() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcTDDVCSGenDict() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
  G__cpp_setup_func13();
  G__cpp_setup_func14();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__TDDVCSGenDictLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TNamed = { "TNamed" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTBaselEfloatgR = { "TMatrixTBase<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTBaselEdoublegR = { "TMatrixTBase<double>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TVectorTlEfloatgR = { "TVectorT<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TVectorTlEdoublegR = { "TVectorT<double>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TElementActionTlEfloatgR = { "TElementActionT<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TElementPosActionTlEfloatgR = { "TElementPosActionT<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTlEfloatgR = { "TMatrixT<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTRow_constlEfloatgR = { "TMatrixTRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTRowlEfloatgR = { "TMatrixTRow<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTDiag_constlEfloatgR = { "TMatrixTDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTColumn_constlEfloatgR = { "TMatrixTColumn_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTFlat_constlEfloatgR = { "TMatrixTFlat_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSub_constlEfloatgR = { "TMatrixTSub_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseRow_constlEfloatgR = { "TMatrixTSparseRow_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseDiag_constlEfloatgR = { "TMatrixTSparseDiag_const<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTColumnlEfloatgR = { "TMatrixTColumn<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTDiaglEfloatgR = { "TMatrixTDiag<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTFlatlEfloatgR = { "TMatrixTFlat<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSublEfloatgR = { "TMatrixTSub<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseRowlEfloatgR = { "TMatrixTSparseRow<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseDiaglEfloatgR = { "TMatrixTSparseDiag<float>" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TVector3 = { "TVector3" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TLorentzVector = { "TLorentzVector" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TRandom = { "TRandom" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TRandom3 = { "TRandom3" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TGenPart = { "TGenPart" , 99 , -1 };
G__linked_taginfo G__TDDVCSGenDictLN_TDDVCSGen = { "TDDVCSGen" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableTDDVCSGenDict() {
  G__TDDVCSGenDictLN_TClass.tagnum = -1 ;
  G__TDDVCSGenDictLN_TBuffer.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMemberInspector.tagnum = -1 ;
  G__TDDVCSGenDictLN_TObject.tagnum = -1 ;
  G__TDDVCSGenDictLN_TNamed.tagnum = -1 ;
  G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTBaselEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTBaselEdoublegR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TVectorTlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TVectorTlEdoublegR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TElementActionTlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TElementPosActionTlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTRow_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTRowlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTDiag_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTColumn_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTFlat_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTSub_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTSparseRow_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTSparseDiag_constlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTColumnlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTDiaglEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTFlatlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTSublEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTSparseRowlEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TMatrixTSparseDiaglEfloatgR.tagnum = -1 ;
  G__TDDVCSGenDictLN_TVector3.tagnum = -1 ;
  G__TDDVCSGenDictLN_TLorentzVector.tagnum = -1 ;
  G__TDDVCSGenDictLN_TRandom.tagnum = -1 ;
  G__TDDVCSGenDictLN_TRandom3.tagnum = -1 ;
  G__TDDVCSGenDictLN_TGenPart.tagnum = -1 ;
  G__TDDVCSGenDictLN_TDDVCSGen.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableTDDVCSGenDict() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TClass);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TObject);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TNamed);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTBaselEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTBaselEdoublegR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TVectorTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TVectorTlEdoublegR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TElementActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TElementPosActionTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTColumn_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTFlat_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTSub_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTSparseRow_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTSparseDiag_constlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTColumnlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTFlatlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTSublEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTSparseRowlEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TMatrixTSparseDiaglEfloatgR);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TVector3);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TLorentzVector);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TRandom);
   G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TRandom3);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TGenPart),sizeof(TGenPart),-1,62720,(char*)NULL,G__setup_memvarTGenPart,G__setup_memfuncTGenPart);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__TDDVCSGenDictLN_TDDVCSGen),sizeof(TDDVCSGen),-1,29952,(char*)NULL,G__setup_memvarTDDVCSGen,G__setup_memfuncTDDVCSGen);
}
extern "C" void G__cpp_setupTDDVCSGenDict(void) {
  G__check_setup_version(30051515,"G__cpp_setupTDDVCSGenDict()");
  G__set_cpp_environmentTDDVCSGenDict();
  G__cpp_setup_tagtableTDDVCSGenDict();

  G__cpp_setup_inheritanceTDDVCSGenDict();

  G__cpp_setup_typetableTDDVCSGenDict();

  G__cpp_setup_memvarTDDVCSGenDict();

  G__cpp_setup_memfuncTDDVCSGenDict();
  G__cpp_setup_globalTDDVCSGenDict();
  G__cpp_setup_funcTDDVCSGenDict();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncTDDVCSGenDict();
  return;
}
class G__cpp_setup_initTDDVCSGenDict {
  public:
    G__cpp_setup_initTDDVCSGenDict() { G__add_setup_func("TDDVCSGenDict",(G__incsetup)(&G__cpp_setupTDDVCSGenDict)); G__call_setup_funcs(); }
   ~G__cpp_setup_initTDDVCSGenDict() { G__remove_setup_func("TDDVCSGenDict"); }
};
G__cpp_setup_initTDDVCSGenDict G__cpp_setup_initializerTDDVCSGenDict;

