/********************************************************************
* TDDVCSGenDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error TDDVCSGenDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableTDDVCSGenDict();
extern void G__cpp_setup_inheritanceTDDVCSGenDict();
extern void G__cpp_setup_typetableTDDVCSGenDict();
extern void G__cpp_setup_memvarTDDVCSGenDict();
extern void G__cpp_setup_globalTDDVCSGenDict();
extern void G__cpp_setup_memfuncTDDVCSGenDict();
extern void G__cpp_setup_funcTDDVCSGenDict();
extern void G__set_cpp_environmentTDDVCSGenDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "TDDVCSGen.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__TDDVCSGenDictLN_TClass;
extern G__linked_taginfo G__TDDVCSGenDictLN_TBuffer;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMemberInspector;
extern G__linked_taginfo G__TDDVCSGenDictLN_TObject;
extern G__linked_taginfo G__TDDVCSGenDictLN_TNamed;
extern G__linked_taginfo G__TDDVCSGenDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__TDDVCSGenDictLN_TVector3;
extern G__linked_taginfo G__TDDVCSGenDictLN_TLorentzVector;
extern G__linked_taginfo G__TDDVCSGenDictLN_TRandom;
extern G__linked_taginfo G__TDDVCSGenDictLN_TRandom3;
extern G__linked_taginfo G__TDDVCSGenDictLN_TGenPart;
extern G__linked_taginfo G__TDDVCSGenDictLN_TDDVCSGen;

/* STUB derived class for protected member access */
